<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Ask your first question' => 'Câu hỏi đầu tiên của bạn',
    'Comments' => 'Bình luận',
    'Customer Service' => 'dich vu khach hang',
    'Edit Credential' => 'Sua chung chi',
    'Experiences in Life' => 'Kinh nghiem trong cuoc song',
    'Feeds' => 'Tường',
    'Find your friend on Quora' => 'Tìm kiếm bạn bè trên Quickrep',
    'Go Anonymous' => 'Ẩn danh',
    'Go Fullscreen' => 'Full màn hình',
    'Improve Your Feed' => 'Phat trien trang cua ban',
    'Life Advice' => '',
    'Popular on Quora' => 'Phổ biến trên Quickrep',
    'Respect' => '',
    'Search For Topics to Bookmark' => 'Tim kiem topic de danh dau',
    'Toggle navigation' => '',
    'Top Stories' => 'Câu hỏi hàng đầu',
    'Top Stories For You' => 'Câu hỏi hàng đầu cho bạn',
    'Trending Now' => 'Xu hướng',
    'Turn On Notifications' => '',
    'Upvote 2 more good answers' => '',
    'Visit your feed' => 'Tham trang cua ban',
    'What is your question?' => 'Câu hỏi của bạn là?',
    'Write your answer' => 'Viet cau tra loi',
    'Written' => 'Da viet',
    'Add info about what you know' => 'Thêm thông tin về những gì bạn biết',
    'Answer' => 'Trả lời',
    'Answer a question' => 'Trả lời một câu hỏi',
    'Bookmarked Answers' => 'Đánh dấu câu trả lời',
    'Ask your first question' => '',
    'Bookmarked Answers' => 'Đánh dấu câu trả lời',
    'Ask your first question' => '',
    'Bookmarked Answers' => 'Câu trả lời đã theo dõi',
    'Comment' => 'Bình luận',
    'Downvote' => 'Không tốt',
    'Comments' => 'Bình luận',
    'Customer Service' => '',
    'Downvote' => 'Không tốt',
    'Comments' => 'Bình luận',
    'Customer Service' => 'Dịch vụ khách hàng',
    'Downvote' => 'Không tốt',
    'Edit' => 'Sửa',
    'Edit Credential' => '',
    'Experiences in Life' => '',
    'Feeds' => '',
    'Find your friend on Quora' => '',
    'Edit Credential' => 'Chỉnh sửa Giấy chứng nhận',
    'Experiences in Life' => '',
    'Feeds' => '',
    'Find your friend on Quora' => '',
    'Follow' => 'Theo dõi',
    'Follow 14 more topics' => 'Theo dõi thêm 14 chủ đề',
    'Go Anonymous' => '',
    'Go Fullscreen' => '',
    'Improve Your Feed' => 'Cải thiện thông tin của bạn',
    'Life Advice' => '',
    'More Comments' => 'Xem thêm bình luận',
    'Popular on Quora' => '',
    'Popular on Quora' => '',
    'Report' => 'Báo cáo',
    'Upvote' => 'Tốt',
	'Add profile credential'	=> 'Thêm thông tin về bạn',
	'Write a description about yourself'	=> 'Phương châm sống của bạn là gì?',
	'Add employment'	=> 'Thêm một nơi làm việc',
	'Add education'		=> 'Thêm một kỹ năng nghề nghiệp',
	'Add a location'	=> 'Thêm một địa điểm',
	'Credentials &amp; Highlights' => 'Chuyên ngành & Sở trường',
	'Knows About'		=> 'Chủ đề bạn biết',
	'What topics do you know about?' => 'Những chủ đề nào khiến bạn quan tâm?',
	'Following'	=> 'Đang theo dõi',
	'Pass'		=> 'Bỏ qua',
	'Ask Question'	=> 'Đặt câu hỏi',
	'Submit Question'	=> 'Gửi câu hỏi',
	'Read'	=> 'Mới nhất',
	'Notifications'	=> 'Thông báo',
	'Ask or Search Quickrep' => 'Đặt câu hỏi hoặc tìm kiếm với Quickrep',
	'Followers'	=> 'Theo dõi'
	
];
