/*
Navicat MySQL Data Transfer

Source Server         : 127.0.0.1
Source Server Version : 50505
Source Host           : 127.0.0.1:3306
Source Database       : quickrep

Target Server Type    : MYSQL
Target Server Version : 50505
File Encoding         : 65001

Date: 2018-01-02 14:41:16
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for topics
-- ----------------------------
DROP TABLE IF EXISTS `topics`;
CREATE TABLE `topics` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `parent_id` int(11) DEFAULT NULL,
  `topics_group_id` int(11) DEFAULT NULL,
  `quote` tinytext COLLATE utf8_unicode_ci,
  `body` text COLLATE utf8_unicode_ci,
  `images` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `google_title` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `google_description` tinytext COLLATE utf8_unicode_ci,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `status` int(45) NOT NULL DEFAULT '0',
  `slug` tinytext COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=185 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci KEY_BLOCK_SIZE=1;

-- ----------------------------
-- Records of topics
-- ----------------------------
INSERT INTO `topics` VALUES ('65', 'Harry Potter', null, null, 'giới thiệu ngắn harry potter', 'giới thiệu harry potter', 'harry-potter_1496932085.png', '', '', null, null, '1', 'harry-potter');
INSERT INTO `topics` VALUES ('67', 'GOS Entertainment And Media', null, null, null, null, null, null, null, '2017-06-18 23:29:23', null, '1', 'gos-entertainment-and-media');
INSERT INTO `topics` VALUES ('68', 'FPT-Aptech Computer Education', null, null, null, null, null, null, null, '2017-06-18 23:30:24', null, '1', 'fpt-aptech-computer-education');
INSERT INTO `topics` VALUES ('69', 'Công nghệ thông tin', null, null, null, null, null, null, null, '2017-06-18 23:30:39', null, '1', 'cong-nghe-thong-tin');
INSERT INTO `topics` VALUES ('70', '36 Thống Nhất, Gò Vấp, HCM', null, null, null, null, null, null, null, '2017-06-18 23:31:42', null, '1', '36-thong-nhat-go-vap-hcm');
INSERT INTO `topics` VALUES ('71', 'Công ty TNHH tư vấn dịch vụ thuế và kế toán Hải Dương', null, null, null, null, null, null, null, '2017-06-19 21:16:29', null, '1', 'cong-ty-tnhh-tu-van-dich-vu-thue-va-ke-toan-hai-duong');
INSERT INTO `topics` VALUES ('72', 'Đại học lao động xã hội', null, null, null, null, null, null, null, '2017-06-19 21:17:34', null, '1', 'dai-hoc-lao-dong-xa-hoi');
INSERT INTO `topics` VALUES ('73', 'Kế toán tổng hợp', null, null, null, null, null, null, null, '2017-06-19 21:17:45', null, '1', 'ke-toan-tong-hop');
INSERT INTO `topics` VALUES ('74', 'Số 65 Tuệ Tĩnh, Phường Nguyễn Trãi, Tp Hải Dương', null, null, null, null, null, null, null, '2017-06-19 21:19:25', null, '1', 'so-65-tue-tinh-phuong-nguyen-trai-tp-hai-duong');
INSERT INTO `topics` VALUES ('75', '154/4e Hố Nai3 Trảng Bom Đồng Nai', null, null, null, null, null, null, null, '2017-06-19 22:15:00', null, '1', '154-4e-ho-nai3-trang-bom-dong-nai');
INSERT INTO `topics` VALUES ('76', 'Softworld Vietnam', null, null, null, null, null, null, null, '2017-06-19 22:16:42', null, '1', 'softworld-vietnam');
INSERT INTO `topics` VALUES ('77', 'Cao Đẳng Lý Tự Trọng', null, null, null, null, null, null, null, '2017-06-21 21:42:01', null, '1', 'cao-dang-ly-tu-trong');
INSERT INTO `topics` VALUES ('78', 'CNTT', null, null, null, null, null, null, null, '2017-06-21 21:42:08', null, '1', 'cntt');
INSERT INTO `topics` VALUES ('79', 'Ở đâu còn lâu mới nói', null, null, null, null, null, null, null, '2017-06-21 21:42:27', null, '1', 'o-dau-con-lau-moi-noi');
INSERT INTO `topics` VALUES ('80', 'Study', null, null, null, null, null, null, null, '2017-09-27 12:01:16', null, '0', 'study');
INSERT INTO `topics` VALUES ('81', 'quickrep', null, null, null, null, null, null, null, '2017-12-31 09:42:58', null, '0', 'quickrep');
INSERT INTO `topics` VALUES ('82', 'phú quốc', null, null, null, null, null, null, null, '2017-12-31 09:46:14', null, '0', 'phu-quoc');
INSERT INTO `topics` VALUES ('83', 'Sức khoẻ', null, '1', '', '', 'suc-khoe_1514773327.jpeg', '', '', null, null, '0', 'suc-khoe');
INSERT INTO `topics` VALUES ('84', 'Ăn uống lành mạnh', null, '1', 'Tất cả về việc giúp đỡ người khác tìm hiểu thêm về thức ăn mà chúng ta ăn và các công thức nấu ăn để có được sức khỏe tốt hơn.', '', 'an-uong-lanh-manh_1514773387.jpeg', '', '', null, null, '0', 'an-uong-lanh-manh');
INSERT INTO `topics` VALUES ('85', 'Y học và Chăm sóc sức khoẻ', null, '1', 'Bất cứ điều gì liên quan đến y học, y tế, chăm sóc sức khoẻ, điều kiện y tế, bệnh tật, bệnh tật cần được can thiệp y tế, bệnh nhân, công nghệ y tế - nghề nghiệp - nghiên cứu - thủ tục - b', '', 'y-hoc-va-cham-soc-suc-khoe_1514774452.jpeg', '', '', null, null, '0', 'y-hoc-va-cham-soc-suc-khoe');
INSERT INTO `topics` VALUES ('86', 'Tập thể dục', null, '1', '', '', 'tap-the-duc_1514774767.jpeg', '', '', null, null, '0', 'tap-the-duc');
INSERT INTO `topics` VALUES ('87', 'Sống khỏe mạnh', null, '1', '\r\nChủ đề này là về tất cả các khía cạnh của một lối sống lành mạnh, bao gồm ăn uống lành mạnh.', '', 'song-khoe-manh_1514775003.jpeg', '', '', null, null, '0', 'song-khoe-manh');
INSERT INTO `topics` VALUES ('88', 'Dinh dưỡng', null, '1', 'Điều tra phản ứng chuyển hóa và sinh lý của cơ thể đối với chế độ ăn uống. Với những tiến bộ trong lĩnh vực sinh học phân tử, hóa sinh và di truyền học, nghiên cứu về dinh dưỡng đang ngày càng', '', 'dinh-duong_1514775062.jpeg', '', '', null, null, '0', 'dinh-duong');
INSERT INTO `topics` VALUES ('89', 'Sức khoẻ Tinh thần', null, '1', 'Sức khoẻ tâm lý của một người, bao gồm quyền tự chủ và năng lực của cá nhân, và khả năng đạt được tiềm năng trí tuệ và tình cảm.', '', 'suc-khoe-tinh-than_1514775168.jpeg', '', '', null, null, '0', 'suc-khoe-tinh-than');
INSERT INTO `topics` VALUES ('90', 'Lịch sử', null, '4', 'Nghiên cứu về quá khứ.', '', 'lich-su_1514775307.jpeg', '', '', null, null, '0', 'lich-su');
INSERT INTO `topics` VALUES ('91', 'Lịch sử Thế giới', null, '4', 'Lịch sử thế giới, lịch sử toàn cầu hoặc lịch sử xuyên quốc gia (không nên nhầm lẫn với lịch sử ngoại giao hoặc quốc tế) là một lĩnh vực nghiên cứu lịch sử nổi lên như là một lĩnh vực học', '', 'lich-su-the-gioi_1514775382.jpeg', '', '', null, null, '0', 'lich-su-the-gioi');
INSERT INTO `topics` VALUES ('92', 'Chiến tranh Thế giới thứ II', null, '16', 'Chiến tranh thế giới lần thứ hai (WWII hay WW2), còn được gọi là Thế chiến thứ hai, là một cuộc chiến tranh toàn cầu kéo dài từ năm 1939 đến năm 1945, mặc dù xung đột bắt đầu sớm hơn. Nó liên quan', '', 'chien-tranh-the-gioi-thu-ii_1514775615.jpeg', '', '', null, null, '0', 'chien-tranh-the-gioi-thu-ii');
INSERT INTO `topics` VALUES ('93', 'Triết học', null, '4', '\r\nNghiên cứu các vấn đề cơ bản như sự tồn tại, và bản chất của thế giới, thông qua các bài diễn thuyết có tính hệ thống và quan trọng.', '', 'triet-hoc_1514775677.jpeg', '', '', null, null, '0', 'triet-hoc');
INSERT INTO `topics` VALUES ('94', 'Triết học Khoa học', null, '4', '\r\nTriết học của Khoa học liên quan đến các giả định, cơ sở, phương pháp, và hàm ý của khoa học, và với việc sử dụng và công đức của khoa học.', '', 'triet-hoc-khoa-hoc_1514775761.jpeg', '', '', null, null, '0', 'triet-hoc-khoa-hoc');
INSERT INTO `topics` VALUES ('95', 'Sách', null, '5', 'Cuốn sách là một bộ sưu tập gồm các tờ giấy, in, minh hoạ hoặc trống, được làm bằng giấy, vải da, hoặc các vật liệu khác, thường được buộc chặt lại với nhau để làm bản lề một bên.', '', 'sach_1514775904.jpeg', '', '', null, null, '0', 'sach');
INSERT INTO `topics` VALUES ('96', 'Viết', null, '5', '', 'Viết là đại diện của ngôn ngữ trong một môi trường bao gồm việc sử dụng một tập hợp các dấu hiệu hoặc biểu tượng (được gọi là hệ thống viết). Nó được phân biệt với minh họa, chẳng hạn như các bản vẽ hang động và các bức tranh, và bảo quản ngôn ngữ không mang tính biểu tượng thông qua các phương tiện không phải là văn bản, chẳng hạn như các bản ghi âm.\r\n\r\nViết có lẽ bắt nguồn từ kết quả của việc mở rộng chính trị trong các nền văn hoá cổ đại, cần có các phương tiện đáng tin cậy để truyền tải thông tin, duy trì các tài khoản tài chính, lưu giữ hồ sơ lịch sử và các hoạt động tương tự.', 'viet_1514775977.jpeg', '', '', null, null, '0', 'viet');
INSERT INTO `topics` VALUES ('97', 'Văn học', null, '5', 'Tác phẩm văn học.', 'Tác phẩm văn học.', 'van-hoc_1514776164.jpeg', '', '', null, null, '0', 'van-hoc');
INSERT INTO `topics` VALUES ('98', 'Sách Khuyến nghị', null, '5', '', '\r\nYêu cầu đề xuất về sách, ví dụ: Những cuốn sách hay nhất về những người vẽ tranh minh họa là gì?\r\nCâu hỏi thường gặp về đề xuất sách là gì?\r\n\"Bạn trở thành những gì bạn đọc.\"\r\n\"Cho dù bạn bận thế nào đi chăng nữa, bạn vẫn phải tìm thời gian để đọc, hoặc đầu hàng mình vào sự thiếu hiểu biết tự chọn.\" - Confucius', 'sach-khuyen-nghi_1514776246.jpeg', '', '', null, null, '0', 'sach-khuyen-nghi');
INSERT INTO `topics` VALUES ('99', 'Các tiểu thuyết ', null, '5', '', '', 'cac-tieu-thuyet_1514776302.jpeg', '', '', null, null, '0', 'cac-tieu-thuyet');
INSERT INTO `topics` VALUES ('100', 'Đọc', null, '5', 'Các hoạt động xác định của thời đại thông tin kể từ Gutenberg.', 'Các hoạt động xác định của thời đại thông tin kể từ Gutenberg.', 'doc_1514776365.jpeg', '', '', null, null, '0', 'doc');
INSERT INTO `topics` VALUES ('101', 'Truyện cổ tích', null, '5', 'Chứa tất cả mọi thứ ngoại trừ thực tại thuần túy.', 'Chứa tất cả mọi thứ ngoại trừ thực tại thuần túy.', 'truyen-co-tich_1514776431.jpeg', '', '', null, null, '0', 'truyen-co-tich');
INSERT INTO `topics` VALUES ('102', 'Văn chương', null, '5', '', '', 'van-chuong_1514776483.jpeg', '', '', null, null, '0', 'van-chuong');
INSERT INTO `topics` VALUES ('103', 'Công nghệ', null, '6', 'Việc ứng dụng thực tế của kiến ​​thức và khoa học.', 'Việc ứng dụng thực tế của kiến ​​thức và khoa học.', 'cong-nghe_1514776591.jpeg', '', '', null, null, '0', 'cong-nghe');
INSERT INTO `topics` VALUES ('104', 'Khoa học', null, '6', 'Hoạt động trí tuệ và thực tiễn bao gồm nghiên cứu có hệ thống về cấu trúc và hành vi của thế giới vật chất và tự nhiên.\r\n- Chủ đề trung tâm về khoa học tự nhiên và tự nhiên, ví dụ: Hóa học', 'Hoạt động trí tuệ và thực tiễn bao gồm nghiên cứu có hệ thống về cấu trúc và hành vi của thế giới vật chất và tự nhiên.\r\n- Chủ đề trung tâm về khoa học tự nhiên và tự nhiên, ví dụ: Hóa học, Sinh học, và Vật lý. Ngoài ra xem Khoa học Xã hội.\r\n- Các câu hỏi liên quan đến các chủ đề Khoa học và Tôn giáo cần được đánh dấu một cách có liên quan hơn theo chủ đề \'Khoa học và Tôn giáo\'.', 'khoa-hoc_1514776688.jpeg', '', '', null, null, '0', 'khoa-hoc');
INSERT INTO `topics` VALUES ('105', 'Khoa học Máy tính', null, '6', 'Khoa học Máy tính là phương pháp khoa học để tính toán.\r\nCác câu hỏi về lập trình nên được thêm vào chương trình máy tính. Các câu hỏi về giáo dục hoặc học về khoa học máy tính nên được đặt tr', 'Khoa học Máy tính là phương pháp khoa học để tính toán.\r\nCác câu hỏi về lập trình nên được thêm vào chương trình máy tính. Các câu hỏi về giáo dục hoặc học về khoa học máy tính nên được đặt trong Giáo dục Khoa học Máy tính hoặc Học về Khoa học Máy tính. Các câu hỏi về công việc hoặc sự nghiệp trong khoa học máy tính nên được đặt trong Jobs and Careers in Computer Science.', 'khoa-hoc-may-tinh_1514776791.jpeg', '', '', null, null, '0', 'khoa-hoc-may-tinh');
INSERT INTO `topics` VALUES ('106', 'Vật lý', null, '6', 'Nghiên cứu vật chất và chuyển động của nó qua không gian và thời gian, cũng như nghiên cứu một số chủ đề liên quan của nó - năng lượng và vũ lực.', 'Nghiên cứu vật chất và chuyển động của nó qua không gian và thời gian, cũng như nghiên cứu một số chủ đề liên quan của nó - năng lượng và vũ lực.', 'vat-ly_1514776845.jpeg', '', '', null, null, '0', 'vat-ly');
INSERT INTO `topics` VALUES ('107', 'Tâm lý học', null, '6', 'Tâm lý học là nghiên cứu tâm trí và hành vi. Đó là một kỷ luật học thuật và một khoa học ứng dụng nhằm tìm hiểu các cá nhân và các nhóm bằng cách thiết lập các nguyên tắc chung và nghiên cứu các', 'Tâm lý học là nghiên cứu tâm trí và hành vi. Đó là một kỷ luật học thuật và một khoa học ứng dụng nhằm tìm hiểu các cá nhân và các nhóm bằng cách thiết lập các nguyên tắc chung và nghiên cứu các trường hợp cụ thể. Trong lĩnh vực này, một chuyên gia hoặc nhà nghiên cứu được gọi là nhà tâm lý học và có thể được phân loại là một nhà khoa học xã hội, hành vi hoặc nhận thức. Các nhà tâm lý học cố gắng hiểu được vai trò của các chức năng tâm thần trong hành vi cá nhân và xã hội, đồng thời khám phá các quá trình sinh lý và sinh học làm cơ sở cho các chức năng nhận thức và hành vi.\r\n', 'tam-ly-hoc_1514776955.jpeg', '', '', null, null, '0', 'tam-ly-hoc');
INSERT INTO `topics` VALUES ('108', 'Kinh tế', null, '6', 'Khoa học xã hội liên quan đến việc mô tả và phân tích sản xuất, phân phối và tiêu thụ hàng hoá và dịch vụ.\r\nBao gồm lý thuyết kinh tế, nguyên tắc và thực tiễn, cũng như điều kiện kinh tế.', 'Khoa học xã hội liên quan đến việc mô tả và phân tích sản xuất, phân phối và tiêu thụ hàng hoá và dịch vụ.\r\nBao gồm lý thuyết kinh tế, nguyên tắc và thực tiễn, cũng như điều kiện kinh tế.', 'kinh-te_1514777050.jpeg', '', '', null, null, '0', 'kinh-te');
INSERT INTO `topics` VALUES ('109', 'Toán học', null, '6', 'Nghiên cứu về số lượng, hình dạng, sự thay đổi, và không gian thông qua việc khấu trừ và suy luận nghiêm ngặt.', 'Nghiên cứu về số lượng, hình dạng, sự thay đổi, và không gian thông qua việc khấu trừ và suy luận nghiêm ngặt.', 'toan-hoc_1514777142.jpeg', '', '', null, null, '0', 'toan-hoc');
INSERT INTO `topics` VALUES ('110', 'Xu hướng Công nghệ', null, '6', '', '', 'xu-huong-cong-nghe_1514777226.jpeg', '', '', null, null, '0', 'xu-huong-cong-nghe');
INSERT INTO `topics` VALUES ('111', 'Lập trình Máy tính', null, '6', 'Lập trình máy tính (thường được rút ngắn thành lập trình) là một quá trình dẫn từ một sự hình thành ban đầu của một vấn đề máy tính đến các chương trình thực thi. Nó bao gồm các hoạt động n', 'Lập trình máy tính (thường được rút ngắn thành lập trình) là một quá trình dẫn từ một sự hình thành ban đầu của một vấn đề máy tính đến các chương trình thực thi. Nó bao gồm các hoạt động như phân tích, hiểu biết, và giải quyết chung các vấn đề như vậy dẫn đến một thuật toán, xác minh các yêu cầu của thuật toán bao gồm tính chính xác của nó và tiêu thụ tài nguyên của nó, thực hiện (thường được gọi là mã hóa) của thuật toán trong một ngôn ngữ lập trình mục tiêu, thử nghiệm, gỡ lỗi và duy trì mã nguồn, thực hiện xây dựng hệ thống và quản lý các sản phẩm có nguồn gốc, chẳng hạn như mã máy của các chương trình máy tính.\r\n', 'lap-trinh-may-tinh_1514777279.jpeg', '', '', null, null, '0', 'lap-trinh-may-tinh');
INSERT INTO `topics` VALUES ('112', 'Kỹ thuật Phần mềm', null, '6', 'Kỹ thuật Phần mềm (SE) là một nghề chuyên dụng để thiết kế, triển khai, sửa đổi và xác nhận phần mềm để nó có chất lượng cao hơn, giá cả phải chăng hơn, có thể duy trì và nhanh hơn để xây d', 'Kỹ thuật Phần mềm (SE) là một nghề chuyên dụng để thiết kế, triển khai, sửa đổi và xác nhận phần mềm để nó có chất lượng cao hơn, giá cả phải chăng hơn, có thể duy trì và nhanh hơn để xây dựng.\r\n\"Mô phỏng của thế giới thực với thế giới số\"', 'ky-thuat-phan-mem_1514777350.jpeg', '', '', null, null, '0', 'ky-thuat-phan-mem');
INSERT INTO `topics` VALUES ('113', 'Trí tuệ nhân tạo', null, '16', 'Học máy là nghiên cứu các thuật toán máy tính cải tiến tự động thông qua kinh nghiệm và là trung tâm của các nghiên cứu về AI từ khi bắt đầu thực địa.', 'Học máy là nghiên cứu các thuật toán máy tính cải tiến tự động thông qua kinh nghiệm và là trung tâm của các nghiên cứu về AI từ khi bắt đầu thực địa.', 'tri-tue-nhan-tao_1514777421.jpeg', '', '', null, null, '0', 'tri-tue-nhan-tao');
INSERT INTO `topics` VALUES ('114', 'Tâm lý Xã hội', null, '6', 'Nghiên cứu về hành vi của con người trong các nhóm xã hội hoặc xã hội, bao gồm cả cách nó bị ảnh hưởng bởi các thành viên được nhận thức trong các nhóm đó và nó ảnh hưởng như thế nào đến nh?', 'Nghiên cứu về hành vi của con người trong các nhóm xã hội hoặc xã hội, bao gồm cả cách nó bị ảnh hưởng bởi các thành viên được nhận thức trong các nhóm đó và nó ảnh hưởng như thế nào đến nhận thức của các thành viên của các nhóm khác. Không Tự Hoàn thiện hoặc Mẹo và Hacks cho Cuộc sống Hàng Ngày.', 'tam-ly-xa-hoi_1514777476.jpeg', '', '', null, null, '0', 'tam-ly-xa-hoi');
INSERT INTO `topics` VALUES ('115', 'Vũ trụ', null, '6', 'Vũ trụ thường được định nghĩa là:\r\n\"tất cả mọi thứ tồn tại\", bao gồm tất cả vật chất, năng lượng, thời gian, các thiên hà, và các nội dung của không gian giữa các thiên hà hoặc: trái đất cùn', 'Vũ trụ thường được định nghĩa là:\r\n\"tất cả mọi thứ tồn tại\", bao gồm tất cả vật chất, năng lượng, thời gian, các thiên hà, và các nội dung của không gian giữa các thiên hà hoặc: trái đất cùng với tất cả cư dân của nó và tạo ra mọi thứ và thời gian', 'vu-tru_1514777546.jpeg', '', '', null, null, '0', 'vu-tru');
INSERT INTO `topics` VALUES ('116', 'Thuật toán', null, '6', 'Thuật toán là một phương pháp được xác định chính xác, có hiệu quả và hữu hạn để tạo ra đầu ra xác định rõ ràng từ đầu vào được xác định rõ.', 'Thuật toán là một phương pháp được xác định chính xác, có hiệu quả và hữu hạn để tạo ra đầu ra xác định rõ ràng từ đầu vào được xác định rõ.', 'thuat-toan_1514777591.jpeg', '', '', null, null, '0', 'thuat-toan');
INSERT INTO `topics` VALUES ('117', 'Thần kinh học', null, '6', 'Khoa học thần kinh là nghiên cứu khoa học về hệ thần kinh. Theo truyền thống, khoa học thần kinh đã được xem như là một chi nhánh của sinh học, nhưng nó đã phát triển để bao gồm một phạm vi rộng cá', 'Khoa học thần kinh là nghiên cứu khoa học về hệ thần kinh. Theo truyền thống, khoa học thần kinh đã được xem như là một chi nhánh của sinh học, nhưng nó đã phát triển để bao gồm một phạm vi rộng các lĩnh vực liên ngành làm việc cùng nhau để làm sáng tỏ chức năng não ở nhiều mức độ điều tra.', 'than-kinh-hoc_1514777677.jpeg', '', '', null, null, '0', 'than-kinh-hoc');
INSERT INTO `topics` VALUES ('118', 'Ngôn ngữ lập trình', null, '6', 'Chủ đề này là dành cho các câu hỏi về ngôn ngữ lập trình nói chung. Nó bao gồm các so sánh các ngôn ngữ, lựa chọn ngôn ngữ, thiết kế ngôn ngữ, lý thuyết và lịch sử. Nó không bao gồm các câu hỏi v', 'Chủ đề này là dành cho các câu hỏi về ngôn ngữ lập trình nói chung. Nó bao gồm các so sánh các ngôn ngữ, lựa chọn ngôn ngữ, thiết kế ngôn ngữ, lý thuyết và lịch sử. Nó không bao gồm các câu hỏi về ngôn ngữ lập trình cụ thể-những người nên đi theo chủ đề cho ngôn ngữ cụ thể.', 'ngon-ngu-lap-trinh_1514777731.jpeg', '', '', null, null, '0', 'ngon-ngu-lap-trinh');
INSERT INTO `topics` VALUES ('119', 'Thống kê (kỷ luật học thuật) ', null, '6', 'Các chi nhánh của toán học đối phó với việc thu thập, phân tích, giải thích, và trình bày các dữ liệu định lượng.', 'Các chi nhánh của toán học đối phó với việc thu thập, phân tích, giải thích, và trình bày các dữ liệu định lượng.', 'thong-ke-ky-luat-hoc-thuat_1514777812.jpeg', '', '', null, null, '0', 'thong-ke-ky-luat-hoc-thuat');
INSERT INTO `topics` VALUES ('120', 'Xác suất (thống kê)', null, '6', 'Khoa học toán học về cơ hội và tính đúng đắn. Đối với Câu hỏi thường gặp về chủ đề, hãy kiểm tra: Câu hỏi thường gặp về xác suất (thống kê) là gì?', 'Khoa học toán học về cơ hội và tính đúng đắn. Đối với Câu hỏi thường gặp về chủ đề, hãy kiểm tra: Câu hỏi thường gặp về xác suất (thống kê) là gì?', 'xac-suat-thong-ke_1514777890.jpeg', '', '', null, null, '0', 'xac-suat-thong-ke');
INSERT INTO `topics` VALUES ('121', 'Thiết kế', null, '10', 'Thiết kế có thể là một danh từ hoặc động từ. Thiết kế là bản fax của một đối tượng không tồn tại.', 'Thiết kế có thể là một danh từ hoặc động từ. Thiết kế là bản fax của một đối tượng không tồn tại.', 'thiet-ke_1514779277.jpeg', '', '', null, null, '0', 'thiet-ke');
INSERT INTO `topics` VALUES ('122', 'Nhiếp ảnh', null, '10', '', '', 'nhiep-anh_1514779335.jpeg', '', '', null, null, '0', 'nhiep-anh');
INSERT INTO `topics` VALUES ('123', 'Thời trang và Phong cách', null, '10', 'Thời trang đề cập đến phong cách hiện hành của quần áo và phụ kiện (giày dép, túi xách, vv) được sản xuất và sử dụng trong một khoảng thời gian cụ thể.\r\nPhong cách đề cập đến một biểu hiện ', 'Thời trang đề cập đến phong cách hiện hành của quần áo và phụ kiện (giày dép, túi xách, vv) được sản xuất và sử dụng trong một khoảng thời gian cụ thể.\r\nPhong cách đề cập đến một biểu hiện đặc biệt của các yếu tố trong một khu vực chủ đề cụ thể. Trong bối cảnh thời trang, nó đề cập đến chế độ ăn mặc đặc trưng của một người.\r\nCả hai thuật ngữ này thường được sử dụng cho nhau.', 'thoi-trang-va-phong-cach_1514779420.jpeg', '', '', null, null, '0', 'thoi-trang-va-phong-cach');
INSERT INTO `topics` VALUES ('124', 'Mỹ Thuật', null, '10', 'Nghệ thuật đánh giá cao về nội dung trí tưởng tượng, thẩm mỹ, trí tuệ của nó, thường là nghệ thuật thị giác', 'Nghệ thuật đánh giá cao về nội dung trí tưởng tượng, thẩm mỹ, trí tuệ của nó, thường là nghệ thuật thị giác', 'my-thuat_1514779465.jpeg', '', '', null, null, '0', 'my-thuat');
INSERT INTO `topics` VALUES ('125', 'Thiết kế Web', null, '10', 'Thực tiễn thiết kế được áp dụng cho các trang web và trang web, bao gồm các mẫu cho blog và các trang web điều khiển hệ thống quản lý nội dung.', 'Thực tiễn thiết kế được áp dụng cho các trang web và trang web, bao gồm các mẫu cho blog và các trang web điều khiển hệ thống quản lý nội dung.', 'thiet-ke-web_1514779516.jpeg', '', '', null, null, '0', 'thiet-ke-web');
INSERT INTO `topics` VALUES ('126', 'Giao diện người dùng', null, '10', '- Giao diện người dùng, trong lĩnh vực thiết kế công nghiệp tương tác giữa người và máy, là không gian nơi các tương tác giữa con người và máy móc xảy ra.\r\n- Màn hình cảm ứng và bàn phím là các giao di', '- Giao diện người dùng, trong lĩnh vực thiết kế công nghiệp tương tác giữa người và máy, là không gian nơi các tương tác giữa con người và máy móc xảy ra.\r\n- Màn hình cảm ứng và bàn phím là các giao diện người dùng phổ biến nhất.', 'giao-dien-nguoi-dung_1514779616.jpeg', '', '', null, null, '0', 'giao-dien-nguoi-dung');
INSERT INTO `topics` VALUES ('127', 'Nhiếp ảnh kỹ thuật số', null, '10', 'Một chủ đề phụ của Nhiếp ảnh, trong đó các vấn đề kỹ thuật số đặc biệt là trọng tâm. Định dạng tệp tin, thao tác hình ảnh số, thẻ nhớ hoặc lưu trữ kỹ thuật số.\r\nBất cứ điều gì liên', 'Một chủ đề phụ của Nhiếp ảnh, trong đó các vấn đề kỹ thuật số đặc biệt là trọng tâm. Định dạng tệp tin, thao tác hình ảnh số, thẻ nhớ hoặc lưu trữ kỹ thuật số.\r\nBất cứ điều gì liên quan đến tính chất cụ thể của việc sử dụng cảm biến hoặc quá trình xử lý hình ảnh để tạo ra hình ảnh.', 'nhiep-anh-ky-thuat-so_1514779692.jpeg', '', '', null, null, '0', 'nhiep-anh-ky-thuat-so');
INSERT INTO `topics` VALUES ('128', 'Thiết kế sản phẩm hàng hoá hiện vật', null, '10', 'Việc thiết kế các sản phẩm có thể tiếp tục tồn tại ngay cả khi internet biến mất.', 'Việc thiết kế các sản phẩm có thể tiếp tục tồn tại ngay cả khi internet biến mất.', 'thiet-ke-san-pham-hang-hoa-hien-vat_1514779749.jpeg', '', '', null, null, '0', 'thiet-ke-san-pham-hang-hoa-hien-vat');
INSERT INTO `topics` VALUES ('129', 'Quần áo và Trang phục', null, '10', 'Quần áo là chất xơ và vật liệu dệt đeo trên cơ thể. Việc mặc quần áo chủ yếu là hạn chế đối với con người và là một tính năng của gần như tất cả các xã hội loài người. Số lượng và lo?', 'Quần áo là chất xơ và vật liệu dệt đeo trên cơ thể. Việc mặc quần áo chủ yếu là hạn chế đối với con người và là một tính năng của gần như tất cả các xã hội loài người. Số lượng và loại quần áo mòn phụ thuộc vào các cân nhắc về thể chất, xã hội và địa lý. Đó là chức năng chính là để phục vụ như là một phương tiện của cả sự thoải mái và bảo vệ khỏi các yếu tố môi trường. Đó là thông qua là một xã hội hiện đại, cộng đồng và chấp nhận pháp luật bình thường. Morden', 'quan-ao-va-trang-phuc_1514779795.jpeg', '', '', null, null, '0', 'quan-ao-va-trang-phuc');
INSERT INTO `topics` VALUES ('130', 'Báo chí', null, '14', 'Hành động tạo ra những lời kể có ý nghĩa sau khi thu thập, lọc và phân phối thông tin từ các nguồn khác nhau một cách kịp thời, hùng hồn, chính xác, đáng tin cậy, độc lập và có lợi cho xã hội.', 'Hành động tạo ra những lời kể có ý nghĩa sau khi thu thập, lọc và phân phối thông tin từ các nguồn khác nhau một cách kịp thời, hùng hồn, chính xác, đáng tin cậy, độc lập và có lợi cho xã hội.', 'bao-chi_1514865461.jpeg', '', '', null, null, '0', 'bao-chi');
INSERT INTO `topics` VALUES ('131', 'Giải trí', null, '14', 'Giải trí là một hoạt động, sự kiện hoặc hoạt động nhằm mục đích giải trí, vui chơi và quan tâm đến công chúng. Đối tượng này có thể có vai trò thụ động, như trong trường hợp một vở kịch, ', 'Giải trí là một hoạt động, sự kiện hoặc hoạt động nhằm mục đích giải trí, vui chơi và quan tâm đến công chúng. Đối tượng này có thể có vai trò thụ động, như trong trường hợp một vở kịch, một chương trình trên TV hoặc một bộ phim, hoặc đang hoạt động, như trong trường hợp trò chơi điện tử. Hình thức hoạt động tích cực của vui chơi, chẳng hạn như thể thao, thường được coi là giải trí.', 'giai-tri_1514865539.jpeg', '', '', null, null, '0', 'giai-tri');
INSERT INTO `topics` VALUES ('132', 'Phim', null, '14', 'Một chủ đề lớn bao gồm các kết quả của sản xuất phim. Trong khi nhiều chủ đề phụ cụ thể (như Phim kinh dị và Phim Hành động) tồn tại, đây là chiếc dù lớn để nói về bất kỳ bộ phim điện ?', 'Một chủ đề lớn bao gồm các kết quả của sản xuất phim. Trong khi nhiều chủ đề phụ cụ thể (như Phim kinh dị và Phim Hành động) tồn tại, đây là chiếc dù lớn để nói về bất kỳ bộ phim điện ảnh nào được trình chiếu trên sân khấu trước đó.\r\nNếu bạn có câu hỏi về quá trình làm phim và những người làm như vậy, vui lòng thử nhiều chủ đề cụ thể hơn như Đạo diễn phim và Điện ảnh.', 'phim_1514865616.jpeg', '', '', null, null, '0', 'phim');
INSERT INTO `topics` VALUES ('133', 'Âm nhạc', null, '14', 'Nghệ thuật kết hợp giữa âm thanh và sự im lặng và đôi khi từ ngữ và bài trừu tượng để tạo ra một trải nghiệm chủ quan về vẻ đẹp, thường liên quan đến biểu hiện cảm xúc.', 'Nghệ thuật kết hợp giữa âm thanh và sự im lặng và đôi khi từ ngữ và bài trừu tượng để tạo ra một trải nghiệm chủ quan về vẻ đẹp, thường liên quan đến biểu hiện cảm xúc.', 'am-nhac_1514865669.jpeg', '', '', null, null, '0', 'am-nhac');
INSERT INTO `topics` VALUES ('134', 'Nhạc sĩ', null, '14', '', '', 'nhac-si_1514865711.jpeg', '', '', null, null, '0', 'nhac-si');
INSERT INTO `topics` VALUES ('135', 'Truyền hình', null, '14', 'Một tivi (cũng có tivi, truyền hình hay ống) là một máy có màn hình. Tivi được phát tín hiệu và biến chúng thành hình ảnh và âm thanh.', 'Một tivi (cũng có tivi, truyền hình hay ống) là một máy có màn hình. Tivi được phát tín hiệu và biến chúng thành hình ảnh và âm thanh.', 'truyen-hinh_1514865783.jpeg', '', '', null, null, '0', 'truyen-hinh');
INSERT INTO `topics` VALUES ('136', 'Phim truyền hình', null, '14', '', '', 'phim-truyen-hinh_1514865830.jpeg', '', '', null, null, '0', 'phim-truyen-hinh');
INSERT INTO `topics` VALUES ('137', 'Thực phẩm', null, '17', 'Thực phẩm là về các thành phần mà đi vào Nấu ăn, có lẽ theo Recipes. Thực phẩm là chất cung cấp dinh dưỡng cho sinh vật sống (con người, động vật hoặc thực vật).', 'Thực phẩm là về các thành phần mà đi vào Nấu ăn, có lẽ theo Recipes. Thực phẩm là chất cung cấp dinh dưỡng cho sinh vật sống (con người, động vật hoặc thực vật).', 'thuc-pham_1514865947.jpeg', '', '', null, null, '0', 'thuc-pham');
INSERT INTO `topics` VALUES ('138', 'Nấu ăn', null, '17', 'Nấu nướng - hành động áp dụng nhiệt, lạnh, axit, hoặc kiềm vào các phần ăn được và ăn được, giải quyết hương vị và tạo ra một sản phẩm ngon miệng trong quá trình.', 'Nấu nướng - hành động áp dụng nhiệt, lạnh, axit, hoặc kiềm vào các phần ăn được và ăn được, giải quyết hương vị và tạo ra một sản phẩm ngon miệng trong quá trình.', 'nau-an_1514866082.jpeg', '', '', null, null, '0', 'nau-an');
INSERT INTO `topics` VALUES ('139', 'Công thức nấu ăn', null, '17', 'Công thức nấu ăn là hướng dẫn để Nấu ăn hoặc Chuẩn bị Thực phẩm. Các công thức nấu ăn thường bao gồm các đặc điểm của thành phần (phẩm chất và số lượng), các quy trình phải tuân theo, thi?', 'Công thức nấu ăn là hướng dẫn để Nấu ăn hoặc Chuẩn bị Thực phẩm. Các công thức nấu ăn thường bao gồm các đặc điểm của thành phần (phẩm chất và số lượng), các quy trình phải tuân theo, thiết bị được sử dụng, nhiệt độ và thời gian nấu.', 'cong-thuc-nau-an_1514866306.jpeg', '', '', null, null, '0', 'cong-thuc-nau-an');
INSERT INTO `topics` VALUES ('140', 'Nhà hàng', null, '17', 'Các cơ sở phục vụ thức ăn và đồ uống cho khách hàng để đổi lấy tiền.', 'Các cơ sở phục vụ thức ăn và đồ uống cho khách hàng để đổi lấy tiền.', 'nha-hang_1514866400.jpeg', '', '', null, null, '0', 'nha-hang');
INSERT INTO `topics` VALUES ('141', 'Khởi nghiệp ( Startups )', null, '7', 'Khởi động là một tổ chức được thành lập để tìm kiếm một mô hình kinh doanh có thể lặp lại và có thể mở rộng. Các sản phẩm khởi nghiệp thường có xu hướng tập trung vào sản phẩm và đặc t', 'Khởi động là một tổ chức được thành lập để tìm kiếm một mô hình kinh doanh có thể lặp lại và có thể mở rộng. Các sản phẩm khởi nghiệp thường có xu hướng tập trung vào sản phẩm và đặc trưng bởi sự đổi mới.', 'khoi-nghiep-startups_1514868133.jpeg', '', '', null, null, '0', 'khoi-nghiep-startups');
INSERT INTO `topics` VALUES ('142', 'Bắt đầu khởi nghiệp', null, '7', 'Xem Tóm tắt Đánh giá Kinh doanh Harvard của Lean Startup ở đây: Tại sao sự thay đổi của Lean thay đổi Tất cả mọi thứ để tìm hiểu các khái niệm khởi động lean, bấm vào đây: Các Lean Startup, Eric Ries \'O', 'Xem Tóm tắt Đánh giá Kinh doanh Harvard của Lean Startup ở đây: Tại sao sự thay đổi của Lean thay đổi Tất cả mọi thứ để tìm hiểu các khái niệm khởi động lean, bấm vào đây: Các Lean Startup, Eric Ries \'Online Course', 'bat-dau-khoi-nghiep_1514869249.jpeg', '', '', null, null, '0', 'bat-dau-khoi-nghiep');
INSERT INTO `topics` VALUES ('143', 'Người sáng lập và doanh nghiệp', null, '7', 'Một người thiết lập một doanh nghiệp hoặc doanh nghiệp, chịu rủi ro tài chính với hy vọng lợi nhuận.', 'Một người thiết lập một doanh nghiệp hoặc doanh nghiệp, chịu rủi ro tài chính với hy vọng lợi nhuận.', 'nguoi-sang-lap-va-doanh-nghiep_1514869391.jpeg', '', '', null, null, '0', 'nguoi-sang-lap-va-doanh-nghiep');
INSERT INTO `topics` VALUES ('144', 'Chiến lược khởi nghiệp', null, '7', 'Chiến lược khởi động là về các nguyên tắc chung cần thiết để khởi động thành công. Điều này khác với Lời khuyên khởi động là về lời khuyên cho các tình huống khởi động cụ thể.', 'Chiến lược khởi động là về các nguyên tắc chung cần thiết để khởi động thành công. Điều này khác với Lời khuyên khởi động là về lời khuyên cho các tình huống khởi động cụ thể.', 'chien-luoc-khoi-nghiep_1514869485.jpeg', '', '', null, null, '0', 'chien-luoc-khoi-nghiep');
INSERT INTO `topics` VALUES ('145', 'Vốn đầu tư mạo hiểm', null, '7', 'Vốn đầu tư mạo hiểm (còn gọi là VC hay Venture) là một loại vốn cổ phần tư nhân thường cung cấp cho các công ty có tiềm năng tăng trưởng giai đoạn đầu, có tiềm năng tạo ra lợi nhuận thông qua mộ', 'Vốn đầu tư mạo hiểm (còn gọi là VC hay Venture) là một loại vốn cổ phần tư nhân thường cung cấp cho các công ty có tiềm năng tăng trưởng giai đoạn đầu, có tiềm năng tạo ra lợi nhuận thông qua một sự kiện thực hiện cuối cùng như IPO hoặc bán thương mại công ty.', 'von-dau-tu-mao-hiem_1514869551.jpeg', '', '', null, null, '0', 'von-dau-tu-mao-hiem');
INSERT INTO `topics` VALUES ('146', 'Kinh doanh', null, '8', 'Một tổ chức được tạo ra với mục đích cung cấp hàng hoá và / hoặc dịch vụ cho các thực thể có thể có lợi từ chúng.', 'Một tổ chức được tạo ra với mục đích cung cấp hàng hoá và / hoặc dịch vụ cho các thực thể có thể có lợi từ chúng.', 'kinh-doanh_1514869906.jpeg', '', '', null, null, '0', 'kinh-doanh');
INSERT INTO `topics` VALUES ('147', 'Doanh nhân', null, '8', 'Doanh nhân là hành động xác định cơ hội và có nguy cơ biến chúng thành hiện thực.', 'Doanh nhân là hành động xác định cơ hội và có nguy cơ biến chúng thành hiện thực.', 'doanh-nhan_1514869987.jpeg', '', '', null, null, '0', 'doanh-nhan');
INSERT INTO `topics` VALUES ('148', 'Tài chính', null, '8', 'Tài chính là một chi nhánh của nền kinh tế nghiên cứu việc quản lý tiền trong việc tiết kiệm, chi tiêu, cho vay và ngân sách. Thuật ngữ này thường được sử dụng để mô tả hoạt động thương mại tr', 'Tài chính là một chi nhánh của nền kinh tế nghiên cứu việc quản lý tiền trong việc tiết kiệm, chi tiêu, cho vay và ngân sách. Thuật ngữ này thường được sử dụng để mô tả hoạt động thương mại trong việc cung cấp và sắp xếp quỹ cho ba thị trường rộng lớn về kinh doanh, cá nhân và chính phủ.', 'tai-chinh_1514870055.jpeg', '', '', null, null, '0', 'tai-chinh');
INSERT INTO `topics` VALUES ('149', 'Chiến lược kinh doanh', null, '8', 'Chiến lược kinh doanh là một khía cạnh của kế hoạch kinh doanh nhằm cố gắng sắp xếp và sắp xếp các nguồn lực sao cho có được lợi thế cạnh tranh liên quan đến các sự kiện tương lai đã được nh', 'Chiến lược kinh doanh là một khía cạnh của kế hoạch kinh doanh nhằm cố gắng sắp xếp và sắp xếp các nguồn lực sao cho có được lợi thế cạnh tranh liên quan đến các sự kiện tương lai đã được nhận biết hoặc các xu hướng đang phát triển và vị trí của hoạt động kinh doanh với người khác.', 'chien-luoc-kinh-doanh_1514870119.jpeg', '', '', null, null, '0', 'chien-luoc-kinh-doanh');
INSERT INTO `topics` VALUES ('150', 'Tiếp thị', null, '8', 'Tiếp thị là hoạt động, tập hợp các tổ chức, và các quá trình tạo ra, giao tiếp, phân phối và trao đổi các dịch vụ có giá trị cho khách hàng, khách hàng, đối tác và xã hội nói chung.', 'Tiếp thị là hoạt động, tập hợp các tổ chức, và các quá trình tạo ra, giao tiếp, phân phối và trao đổi các dịch vụ có giá trị cho khách hàng, khách hàng, đối tác và xã hội nói chung.', 'tiep-thi_1514870183.jpeg', '', '', null, null, '0', 'tiep-thi');
INSERT INTO `topics` VALUES ('151', 'Đầu tư', null, '8', 'Thực hiện cam kết (tiền hoặc vốn) để thu được lợi nhuận tài chính.', 'Thực hiện cam kết (tiền hoặc vốn) để thu được lợi nhuận tài chính.', 'dau-tu_1514870242.jpeg', '', '', null, null, '0', 'dau-tu');
INSERT INTO `topics` VALUES ('152', 'Mô hình kinh doanh ', null, '8', 'Một mô hình kinh doanh là một phần của chiến lược kinh doanh của một liên doanh. Mô hình kinh doanh giải thích cách thức liên doanh sẽ phối hợp các chức năng của doanh nghiệp để tạo ra, cung cấp và nắm', 'Một mô hình kinh doanh là một phần của chiến lược kinh doanh của một liên doanh. Mô hình kinh doanh giải thích cách thức liên doanh sẽ phối hợp các chức năng của doanh nghiệp để tạo ra, cung cấp và nắm bắt giá trị theo cách tạo thu nhập bền vững.', 'mo-hinh-kinh-doanh_1514870289.jpeg', '', '', null, null, '0', 'mo-hinh-kinh-doanh');
INSERT INTO `topics` VALUES ('153', 'Thị trường chứng khoán', null, '8', 'Một thị trường chứng khoán hoặc thị trường chứng khoán là một thực thể công cộng (một mạng lưới lỏng lẻo của các giao dịch kinh tế, không phải là một cơ sở vật chất hoặc một thực thể r??', 'Một thị trường chứng khoán hoặc thị trường chứng khoán là một thực thể công cộng (một mạng lưới lỏng lẻo của các giao dịch kinh tế, không phải là một cơ sở vật chất hoặc một thực thể rời rạc) cho việc kinh doanh cổ phiếu công ty và các công cụ phái sinh với giá thỏa thuận; đây là những chứng khoán được niêm yết trên sàn chứng khoán cũng như các chứng khoán được giao dịch riêng lẻ.', 'thi-truong-chung-khoan_1514870394.jpeg', '', '', null, null, '0', 'thi-truong-chung-khoan');
INSERT INTO `topics` VALUES ('154', 'Tư vấn nghề nghiệp', null, '8', 'Chủ đề này tổng hợp tất cả các nội dung liên quan đến truy vấn nghề nghiệp của bạn', 'Chủ đề này tổng hợp tất cả các nội dung liên quan đến truy vấn nghề nghiệp của bạn', 'tu-van-nghe-nghiep_1514870514.jpeg', '', '', null, null, '0', 'tu-van-nghe-nghiep');
INSERT INTO `topics` VALUES ('155', 'Tài chính cá nhân', null, '8', 'Tài chính cá nhân là việc áp dụng các nguyên tắc về tài chính vào các quyết định tiền tệ của một cá nhân hoặc một đơn vị gia đình. Nó giải quyết các cách thức mà các cá nhân hoặc gia đình có ?', 'Tài chính cá nhân là việc áp dụng các nguyên tắc về tài chính vào các quyết định tiền tệ của một cá nhân hoặc một đơn vị gia đình. Nó giải quyết các cách thức mà các cá nhân hoặc gia đình có được, ngân sách, tiết kiệm và chi tiêu các nguồn tài chính theo thời gian, có tính đến các rủi ro tài chính khác nhau và các sự kiện trong tương lai của cuộc sống. Các thành phần của tài chính cá nhân có thể bao gồm kiểm tra và tài khoản tiết kiệm, thẻ tín dụng và cho vay tiêu dùng, đầu tư vào thị trường chứng khoán, kế hoạch nghỉ hưu, phúc lợi xã hội, chính sách bảo hiểm và quản lý thuế thu nhập. ( nguồn Wikipedia)', 'tai-chinh-ca-nhan_1514870838.jpeg', '', '', null, null, '0', 'tai-chinh-ca-nhan');
INSERT INTO `topics` VALUES ('156', 'Tiền', null, '8', '', '', 'tien_1514870908.jpeg', '', '', null, null, '0', 'tien');
INSERT INTO `topics` VALUES ('157', 'Tham quan và Du lịch', null, '12', 'Để tránh xa môi trường làm việc của mình, theo một nghĩa nào đó, thoát khỏi cái tôi của mình; và điều này thường là lợi thế chính của du lịch và thay đổi.', 'Để tránh xa môi trường làm việc của mình, theo một nghĩa nào đó, thoát khỏi cái tôi của mình; và điều này thường là lợi thế chính của du lịch và thay đổi.', 'tham-quan-va-du-lich_1514871149.jpeg', '', '', null, null, '0', 'tham-quan-va-du-lich');
INSERT INTO `topics` VALUES ('158', 'Du lịch thế giới', null, '12', 'Du lịch giữa hai quốc gia hoặc lục địa.', 'Du lịch giữa hai quốc gia hoặc lục địa.', 'du-lich-the-gioi_1514871218.jpeg', '', '', null, null, '0', 'du-lich-the-gioi');
INSERT INTO `topics` VALUES ('159', 'Kì nghỉ', null, '12', '', '', 'ki-nghi_1514871258.jpeg', '', '', null, null, '0', 'ki-nghi');
INSERT INTO `topics` VALUES ('160', 'Tổ chức du lịch', null, '12', 'Du lịch là đi du lịch cho các mục đích vui chơi giải trí.\r\nChủ đề này đề cập đến việc chia sẻ, gợi ý và giúp đỡ những người có ý tưởng, địa điểm, ý kiến ​​vv, về các điểm đến du lị', 'Du lịch là đi du lịch cho các mục đích vui chơi giải trí.\r\nChủ đề này đề cập đến việc chia sẻ, gợi ý và giúp đỡ những người có ý tưởng, địa điểm, ý kiến ​​vv, về các điểm đến du lịch trên khắp thế giới.', 'to-chuc-du-lich_1514871348.jpeg', '', '', null, null, '0', 'to-chuc-du-lich');
INSERT INTO `topics` VALUES ('161', 'Travel Hacks', null, '12', 'Mẹo và lời khuyên về du lịch', 'Mẹo và lời khuyên về du lịch', 'travel-hacks_1514871786.jpeg', '', '', null, null, '0', 'travel-hacks');
INSERT INTO `topics` VALUES ('162', 'Thể thao', null, '12', '', '', 'the-thao_1514871833.jpeg', '', '', null, null, '0', 'the-thao');
INSERT INTO `topics` VALUES ('163', 'Bóng đá', null, '12', 'Hiệp hội bóng đá, thường được gọi là bóng đá hay bóng đá, là một môn thể thao được chơi giữa hai đội của mười một người chơi với một quả cầu. Trò chơi được chơi trên một trường chữ n', 'Hiệp hội bóng đá, thường được gọi là bóng đá hay bóng đá, là một môn thể thao được chơi giữa hai đội của mười một người chơi với một quả cầu. Trò chơi được chơi trên một trường chữ nhật với một mục tiêu ở mỗi đầu. Các đối tượng của trò chơi là số điểm bằng cách đá bóng vào mục tiêu của đối phương. Nó được chơi bởi 250 triệu người chơi ở hơn 200 quốc gia, làm cho nó trở thành môn thể thao phổ biến nhất thế giới.', 'bong-da_1514871934.jpeg', '', '', null, null, '0', 'bong-da');
INSERT INTO `topics` VALUES ('164', 'Giáo dục', null, '13', 'Nghệ thuật và khoa học về cải tiến tư duy, kiến ​​thức, kỹ năng và giá trị.', 'Nghệ thuật và khoa học về cải tiến tư duy, kiến ​​thức, kỹ năng và giá trị.', 'giao-duc_1514872024.jpeg', '', '', null, null, '0', 'giao-duc');
INSERT INTO `topics` VALUES ('165', 'Nghiên cứu khoa học', null, '13', 'Chủ đề này là để thảo luận về nghiên cứu khoa học như là một nỗ lực. Các ví dụ cụ thể về nghiên cứu khoa học không nên được gắn nhãn với \"Nghiên cứu Khoa học\", nhưng cần được gắn thẻ v', 'Chủ đề này là để thảo luận về nghiên cứu khoa học như là một nỗ lực. Các ví dụ cụ thể về nghiên cứu khoa học không nên được gắn nhãn với \"Nghiên cứu Khoa học\", nhưng cần được gắn thẻ với các chủ đề mà chúng nằm dưới, trừ khi chúng có tiềm ẩn khả năng liên quan đến các lĩnh vực khác của khoa học (nếu không chúng ta sẽ có hàng nghìn đề tài được gắn thẻ điều này).\r\n\r\nĐối với yếu tố con người trong nghiên cứu khoa học, xem các nhà khoa học và tâm lý học về khoa học. Đối với các tổ chức mà nghiên cứu như vậy thường được tiến hành, xem Academia và Graduate School Education', 'nghien-cuu-khoa-hoc_1514872296.jpeg', '', '', null, null, '0', 'nghien-cuu-khoa-hoc');
INSERT INTO `topics` VALUES ('166', 'Giáo dục Đại học', null, '13', 'Giáo dục đại học là giáo dục sau trung học. Đối với các câu hỏi về các trường đại học cụ thể xem các trường Cao đẳng và Đại học. Nếu có thắc mắc về việc học đại học, xem Kinh nghiệm c?', 'Giáo dục đại học là giáo dục sau trung học. Đối với các câu hỏi về các trường đại học cụ thể xem các trường Cao đẳng và Đại học. Nếu có thắc mắc về việc học đại học, xem Kinh nghiệm của trường đại học và trường đại học. Đối với các câu hỏi liên quan đến giáo dục đại học xem Graduate School Education. Đối với các câu hỏi về tuyển sinh, xem Tuyển sinh đại học và Đại học', 'giao-duc-dai-hoc_1514872352.jpeg', '', '', null, null, '0', 'giao-duc-dai-hoc');
INSERT INTO `topics` VALUES ('167', 'TED', null, '13', 'TED là một tổ chức phi lợi nhuận dành cho việc truyền bá ý tưởng, thường là dưới hình thức các cuộc đàm phán ngắn, mạnh mẽ (18 phút hoặc ít hơn). TED bắt đầu vào năm 1984 như là một hội nghị h', 'TED là một tổ chức phi lợi nhuận dành cho việc truyền bá ý tưởng, thường là dưới hình thức các cuộc đàm phán ngắn, mạnh mẽ (18 phút hoặc ít hơn). TED bắt đầu vào năm 1984 như là một hội nghị hội tụ Công nghệ, Giải trí và Thiết kế, và ngày nay bao gồm gần như tất cả các chủ đề - từ khoa học đến doanh nghiệp đến các vấn đề toàn cầu - trong hơn 100 ngôn ngữ. Trong khi đó, các sự kiện TEDx độc lập giúp chia sẻ ý tưởng trong các cộng đồng khắp thế giới.\r\n\r\nThông tin thêm có sẵn trên http://www.ted.com.', 'ted_1514872435.jpeg', '', '', null, null, '0', 'ted');
INSERT INTO `topics` VALUES ('168', 'Đại học và Kinh nghiệm Đại học', null, '13', '', '', 'dai-hoc-va-kinh-nghiem-dai-hoc_1514872791.jpeg', '', '', null, null, '0', 'dai-hoc-va-kinh-nghiem-dai-hoc');
INSERT INTO `topics` VALUES ('169', 'Giáo dục Cao học', null, '13', 'Để vào học tại trường Graduate, xem Graduate Admissions School.\r\nĐối với các chủ đề rộng hơn, xem Academia và nghiên cứu khoa học', 'Để vào học tại trường Graduate, xem Graduate Admissions School.\r\nĐối với các chủ đề rộng hơn, xem Academia và nghiên cứu khoa học', 'giao-duc-cao-hoc_1514873219.jpeg', '', '', null, null, '0', 'giao-duc-cao-hoc');
INSERT INTO `topics` VALUES ('170', 'Hẹn hò và mối quan hệ ', null, '15', 'Chủ đề này bao gồm các nỗ lực cốt lõi của con người tìm kiếm một người nào đó bạn có thể hạnh phúc với, giữ cho họ và bản thân hạnh phúc trong mối quan hệ, và làm thế nào để đối phó vớ', 'Chủ đề này bao gồm các nỗ lực cốt lõi của con người tìm kiếm một người nào đó bạn có thể hạnh phúc với, giữ cho họ và bản thân hạnh phúc trong mối quan hệ, và làm thế nào để đối phó với những vấn đề không thể tránh khỏi đó mọc lên khi mọi người gần gũi.', 'hen-ho-va-moi-quan-he_1514873646.jpeg', '', '', null, null, '0', 'hen-ho-va-moi-quan-he');
INSERT INTO `topics` VALUES ('171', 'Cuộc sống', null, '15', 'Khoảng thời gian can thiệp giữa sinh và tử.', 'Khoảng thời gian can thiệp giữa sinh và tử.', 'cuoc-song_1514873752.jpeg', '', '', null, null, '0', 'cuoc-song');
INSERT INTO `topics` VALUES ('172', 'Tình yêu ', null, '15', 'Một cảm giác sâu thẳm, dịu dàng, không thể diễn tả được về tình cảm và sự ân cần đối với một người, chẳng hạn như sự phát sinh từ quan hệ họ hàng, nhận biết phẩm chất hấp dẫn, hoặc ý', 'Một cảm giác sâu thẳm, dịu dàng, không thể diễn tả được về tình cảm và sự ân cần đối với một người, chẳng hạn như sự phát sinh từ quan hệ họ hàng, nhận biết phẩm chất hấp dẫn, hoặc ý thức về tính nhất thể bên dưới.', 'tinh-yeu_1514873898.jpeg', '', '', null, null, '0', 'tinh-yeu');
INSERT INTO `topics` VALUES ('173', 'Tính hài hước ', null, '15', 'humor / hjuːmə /: chất lượng của sự hài hước hay hài hước, đặc biệt là thể hiện trong văn học hoặc lời nói.\r\n \r\nHài hước hoặc hài hước hoặc là khuynh hướng của những trải nghiệm nhận thức đ', 'humor / hjuːmə /: chất lượng của sự hài hước hay hài hước, đặc biệt là thể hiện trong văn học hoặc lời nói.\r\n \r\nHài hước hoặc hài hước hoặc là khuynh hướng của những trải nghiệm nhận thức đặc biệt để kích thích tiếng cười và giải trí. Thuật ngữ này có nguồn gốc từ thuốc ôn hòa của người Hy Lạp cổ đại, nó dạy rằng sự cân bằng của chất lỏng trong cơ thể con người, được gọi là humours (tiếng Latin: hài hước, \"chất lỏng cơ thể\"), kiểm soát sức khoẻ và cảm xúc của con người.\r\n \r\nMọi người ở mọi lứa tuổi và văn hoá đều hài hước. Hầu hết mọi người đều có thể cảm thấy hài hước - tức là, để cười, cười hoặc cười vào một thứ gì đó buồn cười - và do đó được coi là có tính hài hước. Người giả thiết thiếu cảm giác hài hước sẽ có thể tìm thấy hành vi gây ra bởi sự hài hước là không thể giải thích, kỳ lạ, hoặc thậm chí là không hợp lý. Mặc dù cuối cùng quyết định theo sở thích cá nhân, mức độ mà một người cảm thấy hài hước phụ thuộc vào nhiều biến số, bao gồm vị trí địa lý, văn hoá, sự trưởng thành, mức độ giáo dục, trí tuệ và bối cảnh. Ví dụ, trẻ nhỏ có thể ủng hộ nô lệ như các chương trình múa rối hoặc các bộ phim hoạt hình như Punch and Judy hoặc Tom và Jerry, có tính chất thuần túy về thể chất làm cho chúng dễ tiếp cận hơn. Ngược lại, các hình thức hài hước phức tạp hơn như châm biếm đòi hỏi sự hiểu biết về ý nghĩa và bối cảnh xã hội, do đó có xu hướng thu hút khán giả trưởng thành hơn.', 'tinh-hai-huoc_1514873987.jpeg', '', '', null, null, '0', 'tinh-hai-huoc');
INSERT INTO `topics` VALUES ('174', 'Mẹo vặt  cho cuộc sống hàng ngày', null, '15', 'Chủ đề này là để học các kỹ năng sống được áp dụng cho cuộc sống hàng ngày, và \"làm thế nào để\" của cuộc sống hàng ngày.', 'Chủ đề này là để học các kỹ năng sống được áp dụng cho cuộc sống hàng ngày, và \"làm thế nào để\" của cuộc sống hàng ngày.', 'meo-vat-cho-cuoc-song-hang-ngay_1514874157.jpeg', '', '', null, null, '0', 'meo-vat-cho-cuoc-song-hang-ngay');
INSERT INTO `topics` VALUES ('175', 'Bài học cuộc sống', null, '15', 'Những điều mà mọi người đã học được từ cuộc sống.', 'Những điều mà mọi người đã học được từ cuộc sống.', 'bai-hoc-cuoc-song_1514874281.jpeg', '', '', null, null, '0', 'bai-hoc-cuoc-song');
INSERT INTO `topics` VALUES ('176', 'Bạn bè', null, '15', 'Có một số điều trong thế giới này mà những từ không thể mô tả để hoàn thiện, đây là một trong số họ ...', 'Có một số điều trong thế giới này mà những từ không thể mô tả để hoàn thiện, đây là một trong số họ ...', 'ban-be_1514874356.jpeg', '', '', null, null, '0', 'ban-be');
INSERT INTO `topics` VALUES ('177', 'Hài', null, '15', '\"Bốn cấp độ hài hước: Làm bạn bè của bạn cười 2. Làm cho người lạ cười 3. Được trả tiền để khiến người lạ cười 4. Làm cho mọi người nói chuyện như bạn bởi vì nó rất vui. -Jerry Seinfeld', '\"Bốn cấp độ hài hước: Làm bạn bè của bạn cười 2. Làm cho người lạ cười 3. Được trả tiền để khiến người lạ cười 4. Làm cho mọi người nói chuyện như bạn bởi vì nó rất vui. -Jerry Seinfeld', 'hai_1514874507.jpeg', '', '', null, null, '0', 'hai');
INSERT INTO `topics` VALUES ('178', 'Lời khuyên về Cuộc sống ', null, '15', 'Quan sát và suy nghĩ về cách sống tốt hơn', 'Quan sát và suy nghĩ về cách sống tốt hơn', 'loi-khuyen-ve-cuoc-song_1514874616.jpeg', '', '', null, null, '0', 'loi-khuyen-ve-cuoc-song');
INSERT INTO `topics` VALUES ('179', 'Hôn nhân', null, '15', 'Chủ đề này dành cho hôn nhân (dân sự / tôn giáo hoặc tôn giáo). Hôn nhân là mối quan hệ giữa hai người mà là một mối quan hệ đồng thuận và hợp đồng thường được pháp luật công nhận.\r\nĐối vớ', 'Chủ đề này dành cho hôn nhân (dân sự / tôn giáo hoặc tôn giáo). Hôn nhân là mối quan hệ giữa hai người mà là một mối quan hệ đồng thuận và hợp đồng thường được pháp luật công nhận.\r\nĐối với hôn nhân liên quan đến ba hay nhiều bên, xem Polygamy.', 'hon-nhan_1514874750.jpeg', '', '', null, null, '0', 'hon-nhan');
INSERT INTO `topics` VALUES ('180', 'Tư vấn  hẹn hò', null, '15', '', '', 'tu-van-hen-ho_1514875521.jpeg', '', '', null, null, '0', 'tu-van-hen-ho');
INSERT INTO `topics` VALUES ('181', 'YouTube', null, '16', 'YouTube là một trang web chia sẻ video thuộc sở hữu và điều hành bởi http://www.quora.com/Google.', 'YouTube là một trang web chia sẻ video thuộc sở hữu và điều hành bởi http://www.quora.com/Google.', 'youtube_1514878173.jpeg', '', '', null, null, '0', 'youtube');
INSERT INTO `topics` VALUES ('182', 'Google', null, '19', 'Google là một công ty đa quốc gia, chuyên về tìm kiếm Web và quảng cáo trực tuyến. Google lưu trữ và phát triển một số lượng ngày càng tăng các dịch vụ và sản phẩm dựa trên Internet.\r\n\r\nĐối với các ', 'Google là một công ty đa quốc gia, chuyên về tìm kiếm Web và quảng cáo trực tuyến. Google lưu trữ và phát triển một số lượng ngày càng tăng các dịch vụ và sản phẩm dựa trên Internet.\r\n\r\nĐối với các câu hỏi liên quan đến công cụ tìm kiếm, hãy sử dụng Google Tìm kiếm.', 'google_1514878341.jpeg', '', '', null, null, '0', 'google');
INSERT INTO `topics` VALUES ('183', 'Facebook', null, '19', 'Chủ đề này là về sản phẩm, Facebook, có nghĩa là trang web và cộng đồng có liên quan. Đối với các câu hỏi về công ty, xem Facebook (công ty).', 'Chủ đề này là về sản phẩm, Facebook, có nghĩa là trang web và cộng đồng có liên quan. Đối với các câu hỏi về công ty, xem Facebook (công ty).', 'facebook_1514878486.jpeg', '', '', null, null, '0', 'facebook');
INSERT INTO `topics` VALUES ('184', 'Luật', null, '16', '', '', 'luat_1514878645.jpg', '', '', null, null, '0', 'luat');
